[colors.bright]
black =   "0x686868"
blue =    "0x59C2FF"
cyan =    "0x95E6CB"
green =   "0xC2D94C"
magenta = "0xFFEE99"
red =     "0xF07178"
white =   "0xFFFFFF"
yellow =  "0xFFB454"

[colors.normal]
black =   "0x01060E"
blue =    "0x53BDFA"
cyan =    "0x90E1C6"
green =   "0x91B362"
magenta = "0xFAE994"
red =     "0xEA6C73"
white =   "0xC7C7C7"
yellow =  "0xF9AF4F"

[colors.primary]
background = "0x000000"
foreground = "0xEEEEEE"

[font]
size = 16

[font.bold]
family = "Terminess Nerd Font Mono"
style =  "Bold"

[font.bold_italic]
family = "Terminess Nerd Font Mono"
style =  "Bold Italic"

[font.italic]
family = "Terminess Nerd Font Mono"
style =  "Italic"

[font.normal]
family = "Terminess Nerd Font Mono"
style =  "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key =    "N"
mods =   "Control"

[window]
opacity = 0.9
