# theme = "gruvbox_light_soft"
theme = "gruvbox_dark_hard"

[editor]
true-color = true
scrolloff = 1
bufferline = "always"
rulers = [81]

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["read-only-indicator"]
right = ["diagnostics", "file-encoding", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
C-e = ":w"
C-q = ":bc"
C-r = ":rla"
