# theme = "gruvbox_light_hard"
theme = "sunbather"

[editor]
true-color = true
scrolloff = 1
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["read-only-indicator"]
right = ["diagnostics", "file-encoding", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
C-s = ":w"
C-q = ":bc"
