[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
language-servers = ["clangd"]
roots = [".git", "compile_commands.json", ".clangd", ".clang-tidy"]

[language-server.clangd]
command = "clangd"
args = ["--clang-tidy", '--background-index']
config = { "fallbackFlags" = ["-Wall", "-Wextra", "-pedantic"] }

[[language]]
name = "python"
# scope = "source.python"
language-servers = [
  "ruff",
  # "astral-ty",
  "pyrefly",
  # "basedpyright",
]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

# [language-server.astral-ty]
# command = "ty"
# args= ["server"]

# [language-server.basedpyright]
# command = "basedpyright-langserver"
# args = ["--stdio"]
# except-features = ["format", "code-action"]

# [language-server.basedpyright.config.basedpyright.analysis]
# autoSearchPaths = true
# typeCheckingMode = "basic"
# diagnosticMode = "openFilesOnly"

# [language-server.basedpyright.config.basedpyright.analysis.diagnosticSeverityOverrides]
# reportMissingTypeStubs = true
# reportUndefinedVariable = "none" # covered by ruff
# reportUnreachable = "none"
# reportUnusedImport = "none" # covered by ruff
# reportUnusedVariable = "none" # covered by ruff

# [language-server.astral-ty]
# command = "ty"
# args= ["server"]

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[language-server.ruff.config.settings]
configuration = "~/.config/ruff/ruff.toml"
