preview = true
line-length = 80
indent-width = 4

[lint]
select = [
    # Core
    "F",    # Pyflakes
    "E", "W",  # PEP 8
    "B",    # Bugbear
    # "N",    # pep8 naming
    "A",    # Flake-8 builtins
    "C4",   # Flake-8 comprehensions
    "FIX",  # Flake-8 Fixme
    # Type hints
    "ANN",  # Annotations
    # Modern Python
    "UP",   # Pyupgrade
    "RUF",  # Ruff-specific
    # Security
    "S",    # Bandit
    # "T",    # Debugger
    # Performance
    "PERF",
    # Pylint
    "PLC", "PLE", "PLW",
    # isort
    # "I"
]
